[2024-04-23T08:04:11.434+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world_dag.hello_world manual__2024-04-23T08:04:09.380368+00:00 [queued]>
[2024-04-23T08:04:11.443+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world_dag.hello_world manual__2024-04-23T08:04:09.380368+00:00 [queued]>
[2024-04-23T08:04:11.444+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-04-23T08:04:11.457+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): hello_world> on 2024-04-23 08:04:09.380368+00:00
[2024-04-23T08:04:11.461+0000] {standard_task_runner.py:60} INFO - Started process 326 to run task
[2024-04-23T08:04:11.464+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hello_world_dag', 'hello_world', 'manual__2024-04-23T08:04:09.380368+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/test_dags/hello_world_dag.py', '--cfg-path', '/tmp/tmpotp2tv53']
[2024-04-23T08:04:11.467+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask hello_world
[2024-04-23T08:04:11.481+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-23T08:04:11.515+0000] {task_command.py:423} INFO - Running <TaskInstance: hello_world_dag.hello_world manual__2024-04-23T08:04:09.380368+00:00 [running]> on host 91aaf64076e7
[2024-04-23T08:04:11.596+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hello_world_dag' AIRFLOW_CTX_TASK_ID='hello_world' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T08:04:09.380368+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T08:04:09.380368+00:00'
[2024-04-23T08:04:11.597+0000] {uwdr_hook.py:24} INFO - Выполнение запроса: 
    select version()
[2024-04-23T08:04:11.609+0000] {uwdr_hook.py:28} INFO - Запрос выполнен успешно
[2024-04-23T08:04:11.609+0000] {hello_world.py:29} INFO - Текущая версия ClickHouse: 23.12.2.59,
[2024-04-23T08:04:11.902+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/services/hello_world.py", line 35, in hello_world_py
    logger.info(f"Текущая погода в {city}: {data['main']['humidity']}")
KeyError: 'main'
[2024-04-23T08:04:11.913+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=hello_world_dag, task_id=hello_world, execution_date=20240423T080409, start_date=20240423T080411, end_date=20240423T080411
[2024-04-23T08:04:11.924+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 20 for task hello_world ('main'; 326)
[2024-04-23T08:04:11.960+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-23T08:04:11.978+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
