[2024-04-22T12:48:43.524+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world_dag.hello_world manual__2024-04-22T12:46:44.564732+00:00 [queued]>
[2024-04-22T12:48:43.537+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world_dag.hello_world manual__2024-04-22T12:46:44.564732+00:00 [queued]>
[2024-04-22T12:48:43.538+0000] {taskinstance.py:2171} INFO - Starting attempt 3 of 3
[2024-04-22T12:48:43.554+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): hello_world> on 2024-04-22 12:46:44.564732+00:00
[2024-04-22T12:48:43.559+0000] {standard_task_runner.py:60} INFO - Started process 255 to run task
[2024-04-22T12:48:43.562+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hello_world_dag', 'hello_world', 'manual__2024-04-22T12:46:44.564732+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/hello_world_dag.py', '--cfg-path', '/tmp/tmpe0_ofkex']
[2024-04-22T12:48:43.565+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask hello_world
[2024-04-22T12:48:43.584+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-22T12:48:43.628+0000] {task_command.py:423} INFO - Running <TaskInstance: hello_world_dag.hello_world manual__2024-04-22T12:46:44.564732+00:00 [running]> on host c9c55c9ee351
[2024-04-22T12:48:43.715+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hello_world_dag' AIRFLOW_CTX_TASK_ID='hello_world' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T12:46:44.564732+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-22T12:46:44.564732+00:00'
[2024-04-22T12:48:43.732+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/hello_world_dag.py", line 36, in hello_world_py
    logger.info(f"Текущая версия ClickHouse: {result}")
NameError: name 'logger' is not defined
[2024-04-22T12:48:43.747+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=hello_world_dag, task_id=hello_world, execution_date=20240422T124644, start_date=20240422T124843, end_date=20240422T124843
[2024-04-22T12:48:43.763+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task hello_world (name 'logger' is not defined; 255)
[2024-04-22T12:48:43.775+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T12:48:43.801+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
